# Generated by Django 4.2.11 on 2024-05-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=250),
        ),
    ]
