# Generated by Django 4.2.11 on 2024-03-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='note',
            field=models.TextField(blank=True, db_column='description'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
