# Generated by Django 4.2.11 on 2024-05-22 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": (
                    ("search_product", "can search product"),
                    ("export_product", "camn export product"),
                )
            },
        ),
    ]
